version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redis-insight-data:/db

volumes:
  redis-insight-data:
