"""init

Revision ID: b7e38a93edef
Revises: c457243c1ff9
Create Date: 2025-04-03 13:30:25.229768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e38a93edef'
down_revision: Union[str, None] = 'c457243c1ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_profile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_profile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
