"""init

Revision ID: c457243c1ff9
Revises: 2b936fa767da
Create Date: 2025-04-03 12:59:10.865996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c457243c1ff9'
down_revision: Union[str, None] = '2b936fa767da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'name')
    op.drop_column('user_profile', 'email')
    op.drop_column('user_profile', 'google_access_token')
    # ### end Alembic commands ###
